// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCotUuH5hmgPciI41PN5ZjWc5dAp9tKyps',
    appId: '1:385850610740:web:5fef037630ff7ee9b26661',
    messagingSenderId: '385850610740',
    projectId: 'running-app-dee02',
    authDomain: 'running-app-dee02.firebaseapp.com',
    storageBucket: 'running-app-dee02.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDa1UJGDQbzrjc4dq2VZ8d678H0TWrb2Xw',
    appId: '1:385850610740:android:1918153d873e0e9fb26661',
    messagingSenderId: '385850610740',
    projectId: 'running-app-dee02',
    storageBucket: 'running-app-dee02.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuJ4Qp1hlWZJDFXS3SL-R864I2jRQYjpE',
    appId: '1:385850610740:ios:e0ac0fe257d4d292b26661',
    messagingSenderId: '385850610740',
    projectId: 'running-app-dee02',
    storageBucket: 'running-app-dee02.firebasestorage.app',
    iosClientId: '385850610740-i4kebvce0i52454q648a97cq54kgpj92.apps.googleusercontent.com',
    iosBundleId: 'com.example.runningApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuJ4Qp1hlWZJDFXS3SL-R864I2jRQYjpE',
    appId: '1:385850610740:ios:e0ac0fe257d4d292b26661',
    messagingSenderId: '385850610740',
    projectId: 'running-app-dee02',
    storageBucket: 'running-app-dee02.firebasestorage.app',
    iosClientId: '385850610740-i4kebvce0i52454q648a97cq54kgpj92.apps.googleusercontent.com',
    iosBundleId: 'com.example.runningApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCotUuH5hmgPciI41PN5ZjWc5dAp9tKyps',
    appId: '1:385850610740:web:e5fb8c0eb28dd252b26661',
    messagingSenderId: '385850610740',
    projectId: 'running-app-dee02',
    authDomain: 'running-app-dee02.firebaseapp.com',
    storageBucket: 'running-app-dee02.firebasestorage.app',
  );
}
